### ISSUE TITLE
Grammatical correction suggestion?

### ISSUE THREAD

**Issue by TDCLV** [brettcannon/microvenv#34]
Context;

This is why you are always expected to activate a conda environment, as some conda packages require those those shell scripts run. I won't be covering conda environments in this post.

Suggestion;

This is why you are always expected to activate a conda environment, as some conda packages require (-those) those shell scripts (+to be) run. I won't be covering conda environments in this post.

Final;

This is why you are always expected to activate a conda environment, as some conda packages require those shell scripts to be run. I won't be covering conda environments in this post.

I'm not sure if the correction is needed or if the grammatical correction is appropriate.

**Comment by brettcannon** [comment]
Thanks! (Took me a second to realize this was for my blog post and not the README for the project. 😅)
