### ISSUE TITLE
mypy does not check anything

### ISSUE THREAD

**Issue by kbaikov** [brettcannon/microvenv#61]
Hello,

Are you sure that you are invoking mypy correctly? 
If i add incorrect types to some function, e.g. `def create(
    env_dir: int = DEFAULT_ENV_DIR, *, scm_ignore_files: int = frozenset(["git"])
) -> int:` the mypy does not complain.

E.g. `mypy .` invocation is wrong.

I believe you need to give mypy the files directly because it does not recurse into dirs.

**Comment by brettcannon** [comment]
Do have an invocation that shows a different result? I used `nox -s lint` to make mypy happy when it was raising errors.

**Comment by kbaikov** [comment]
If i make the change shown above and run mypy with the affected file argument like this: `mypy microvenv/_create.py`

i get the following errors:

```microvenv on  main (.venv) took 9s 
❯ mypy microvenv/_create.py
microvenv\_create.py:41: error: Missing return statement  [return]
microvenv\_create.py:42: error: Incompatible default for argument "env_dir" (default has type "str", argument has type "int")  [assignment]
microvenv\_create.py:42: error: Incompatible default for argument "scm_ignore_files" (default has type "frozenset[str]", argument has type "int")  [assignment]
microvenv\_create.py:48: error: Argument 1 to "Path" has incompatible type "int"; expected "str | PathLike[str]"  [arg-type]
microvenv\_create.py:81: error: Name "__spec__" is not defined  [name-defined]
microvenv\_create.py:84: error: Name "__spec__" is not defined  [name-defined]
microvenv\_create.py:91: error: No overload variant of "frozenset" matches argument type "int"  [call-overload]
microvenv\_create.py:91: note: Possible overload variants:
microvenv\_create.py:91: note:     def [_T_co] frozenset() -> frozenset[_T_co]
microvenv\_create.py:91: note:     def [_T_co] frozenset(Iterable[_T_co], /) -> frozenset[_T_co]
microvenv\_create.py:95: error: Unsupported operand types for - ("int" and "set[str]")  [operator]
Found 8 errors in 1 file (checked 1 source file)```

**Comment by brettcannon** [comment]
Any interest in submitting a PR to fix it?

**Comment by kbaikov** [comment]
On second thought it works as expected.
According to https://mypy.readthedocs.io/en/stable/running_mypy.html#how-imports-are-found
mypy prefers `.pyi` files first.

And if you delete `_create.pyi` file then your normal invocation `mypy .` will find the `_create.py` file and report the error.

I learned something new.
